$(":checkbox:checked").prop("checked",!1);$("#time").val("");var totalActivityCalories=0,totalIdleCalories=0,minutesFormat=!0,do_once=!0,globalcount=0;window.onload=function(){var a=new Clipboard(".btn");a.on("success",function(a){});a.on("error",function(a){})};var today=new Date,expiry=new Date(today.getTime()+2592E6);function setCookie(a,b){document.cookie=a+"="+escape(b)+"; path=/; expires="+expiry.toGMTString()}
function storeValues(a,b,c,e,f){$("#male").is(":checked")&&(setCookie("gender1",document.getElementById("male").checked),deleteCookie("gender2"));$("#female").is(":checked")&&(setCookie("gender2",document.getElementById("female").checked),deleteCookie("gender1"));setCookie("field1",document.getElementById("field-age").value);setCookie("field2",document.getElementById("field-weight").value);setCookie("field3",document.getElementById("field-feet").value);setCookie("field4",document.getElementById("field-inch").value);
setCookie("field5",document.getElementById("activity-simple").value);setCookie("height_metric",document.getElementById("field-cm").value);$("#metric").is(":checked")?setCookie("field6",document.getElementById("metric").checked):deleteCookie("field6");isNaN(a)||setCookie("field7",a);setCookie("field8",document.getElementById("field-bodyfat").value);setCookie("field9",document.getElementById("field-kcal").value);setCookie("field10",document.getElementById("field-protein").value);setCookie("field11",
document.getElementById("field-carb").value);setCookie("expert_animation_tooltip",do_once);"string"===typeof b&&setCookie("field12",b);0<=c&&3>=c&&setCookie("field13",c);"US"!=e&&"AU"!=e||setCookie("field14",e);0!=f&&1!=f||setCookie("field15",f);setCookie("field16",document.getElementById("table-for-activity").outerHTML);setCookie("field17",totalActivityCalories);setCookie("field18",totalIdleCalories);"min"==document.getElementById("time-format").innerHTML.trim()?setCookie("field19","min"):setCookie("field19",
"hr");return!0}function getCookie(a){a=(new RegExp(a+"=([^;]+)")).exec(document.cookie);return null!=a?unescape(a[1]):null}var expired=new Date(today.getTime()-864E5);function deleteCookie(a){document.cookie=a+"=null; path=/; expires="+expired.toGMTString()}
$(document).ready(function(){var a="US",b={},c={animate_chart:!0,show_chart:!1,slider_calories:!0,country:"US",total_activity_rows:0};$(".slider").slider({value:0,min:-40,max:10,step:1,slide:function(a,d){b.slider=d.value;updateResult(b,c)},stop:function(a,d){updateChart(b,c);storeValues(d.value)}}).slider("pips",{first:"pip",last:"pip",step:10});$("#slider-text-container").on("click",function(a){$("#slider-text-container").hide();c.slider_calories=c.slider_calories?!1:!0;updateResult(b,c);$("#slider-text-container").fadeIn("fast")});
var e=null,f=function(){$(".energy-field").off("click",f);$(".energy-field").addClass("notransition");$(".energy-field").hide();$.when($(".energy-field").fadeIn("fast")).done(function(){$(".energy-field").removeClass("notransition")});c.country="US"==c.country?"AU":"US";c.slider_calories&&$(".slider-title").hide().fadeIn("fast");$("#result-bmr-info, #result-tdee-info").hide().fadeIn("fast");updateResult(b,c);clearTimeout(e);e=setTimeout(function(){c=updateChart(b,c);$(".energy-field").on("click",
f)},200);storeValues("dummyNaN",-1,-1,a)};$(".energy-field").on("click",f);var d,n,g,h,t;if(d=getCookie("gender1"))document.getElementById("male").checked=d,$(".btn-male").addClass("active");if(d=getCookie("gender2"))document.getElementById("female").checked=d,$(".btn-female").addClass("active");if(d=getCookie("field1"))document.getElementById("field-age").value=d;if(d=getCookie("field2"))document.getElementById("field-weight").value=d;if(d=getCookie("field3"))document.getElementById("field-feet").value=
d;if(d=getCookie("field4"))document.getElementById("field-inch").value=d;getCookie("field5")&&(document.getElementById("activity-simple").value=0);if(d=getCookie("height_metric"))document.getElementById("field-cm").value=d;if(d=getCookie("field6"))document.getElementById("metric").checked=d,toggleUnits();if(d=getCookie("field7"))d=parseInt(d),$(".slider").slider("option","value",d),0<d?document.getElementById("amount").innerHTML=" "+d+"% Surplus \u25b2":0==d?document.getElementById("amount").innerHTML=
" "+d+"% Change":document.getElementById("amount").innerHTML=" "+-1*d+"% Deficit \u25bc";if(d=getCookie("field8"))document.getElementById("field-bodyfat").value=d;if(d=getCookie("field9"))document.getElementById("field-kcal").value=d;if(d=getCookie("field10"))document.getElementById("field-protein").value=d;if(d=getCookie("field11"))document.getElementById("field-carb").value=d;if(d=getCookie("expert_animation_tooltip"))do_once=d,do_once="true"==do_once?!0:!1;getCookie("field12");(n=getCookie("field13"))&&
parseInt(n);if(n=getCookie("field14"))a=n;(g=getCookie("field15"))?1==g&&$(".flip-container, #chart-container-weight").fadeIn("slow"):$.ajax({url:"https://freegeoip.net/json/"}).done(function(d){a=d.country_code;c.country=d.country_code;"US"!=c.country&&(document.getElementById("metric").checked=!0,toggleUnits());"AU"!=c.country&&(c.country="NZ"==c.country?"AU":"US");updateResult(b,c)}).fail(function(){updateResult(b,c)});(h=getCookie("field16"))&&$("#table-for-activity").replaceWith(h);if(g=getCookie("field17"))totalActivityCalories=
Number(g);if(g=getCookie("field18"))totalIdleCalories=Number(g);(t=getCookie("field19"))&&"hr"==t&&(document.getElementById("time-format").innerHTML=" hr");b=getInputFields();1<b.activity.tr&&($(".table-activity").fadeIn(),$('#activity-simple option:contains("Sedentary")').text("Select"),$('#activity-expert option:contains("Sedentary")').text("Select"),b=getInputFields(),disableDropdown(b),stripStyle(b));updateResult(b,c);updateChart(b,c);c.animate_chart=!1;$(function(){$('[data-toggle="tooltip"]').tooltip()});
$('[data-toggle="popover"]').popover({placement:"top",trigger:"focus"});$("#activity-info").hover(function(){$("#activity-info").popover("show")},function(){$("#activity-info").popover("hide");$("#activity-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$(".intensity-info").hover(function(){$(".intensity-info").popover("show")},function(){$(".intensity-info").popover("hide")});$("#time-info").hover(function(){$("#time-info").popover("show")},function(){$("#time-info").popover("hide")});
$("#bodyfat-info").hover(function(){$("#bodyfat-info").popover("show")},function(){$("#bodyfat-info").popover("hide")});$("#custom-info").hover(function(){$("#custom-info").popover("show")},function(){$("#custom-info").popover("hide")});$("#protein-info").hover(function(){$("#protein-info").popover("show")},function(){$("#protein-info").popover("hide")});$("#carbs-info").hover(function(){$("#carbs-info").popover("show")},function(){$("#carbs-info").popover("hide")});$("#bmi-info").hover(function(){$("#bmi-info").popover("show")},
function(){$("#bmi-info").popover("hide");$("#bmi-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$("#lbm-info").hover(function(){$("#lbm-info").popover("show")},function(){$("#lbm-info").popover("hide");$("#lbm-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$("#bmr-info").hover(function(){$("#bmr-info").popover("show")},function(){$("#bmr-info").popover("hide");$("#bmr-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$("#tdee-info").hover(function(){$("#tdee-info").popover("show")},
function(){$("#tdee-info").popover("hide");$("#tdee-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$("#protein-column").hover(function(){$("#protein-target").stop().animate({color:"green"},200)},function(){$("#protein-column").popover("hide");$("#protein-target").stop().animate({color:"white"},100)});$("#carbs-column").hover(function(){$("#carbs-limit").stop().animate({color:"red"},200)},function(){$("#carbs-column").popover("hide");$("#carbs-limit").stop().animate({color:"white"},100)});
$("#fat-column").hover(function(){$("#fat-limit").stop().animate({color:"red"},200)},function(){$("#fat-column").popover("hide");$("#fat-limit").stop().animate({color:"white"},100)});$("#resultProtein, #labelProtein, #protein-target").on("click",function(){$("#protein-column").popover("show")});$("#resultCarb, #labelCarb, #carbs-limit").on("click",function(){$("#carbs-column").popover("show")});$("#resultFat, #labelFat, #fat-limit").on("click",function(){$("#fat-column").popover("show")});$(".cell-bmi").on("click",
function(){$("#bmi-info").is(":hover")||$("#bmi-info").animate({backgroundColor:"rgb(13,142,219)"},200)});$(".cell-bmi").hover(function(){},function(){$("#bmi-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$(".cell-lbm").on("click",function(){$("#lbm-info").is(":hover")||$("#lbm-info").animate({backgroundColor:"rgb(13,142,219)"},200)});$(".cell-lbm").hover(function(){},function(){$("#lbm-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$(".cell-bmr").on("click",function(){$("#bmr-info").is(":hover")||
$("#bmr-info").animate({backgroundColor:"rgb(13,142,219)"},200)});$(".cell-bmr").hover(function(){},function(){$("#bmr-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$(".cell-tdee").on("click",function(){$("#tdee-info").is(":hover")||$("#tdee-info").animate({backgroundColor:"rgb(13,142,219)"},200)});$(".cell-tdee").hover(function(){},function(){$("#tdee-info").animate({backgroundColor:"rgb(200,201,202)"},200)});$("#metric-text").hover(function(){$("#metric").is(":checked")||$(this).animate({color:"rgb(119,119,119)"},
100)},function(){$("#metric").is(":checked")||$(this).animate({color:"rgb(169,169,169)"},100)});$("#expert-text").hover(function(){$("#expert").is(":checked")||$(this).animate({color:"rgb(119,119,119)"},100)},function(){$("#expert").is(":checked")||$(this).animate({color:"rgb(169,169,169)"},100)});$("#add-button, #arrow-right").hover(function(){$(this).css({transition:".2s",transform:"scale(1.2)",cursor:"pointer"})},function(){$(this).css({transition:".2s",transform:"scale(1)"})});var l="null",p=
!1;$("body").on("click",function(a){0<$(a.target).parents(".popover.in").length&&"Stats"==l?(document.getElementById("stats-popover-mobile").setAttribute("data-content","Copied!"),$("#stats-popover-mobile").popover("show"),document.getElementById("stats-popover-mobile").setAttribute("data-content","Copy to clipboard."),p=!0,copyToClipboard(c),p=!1,l="null"):$("#stats-popover-mobile").is(":hover")?($("#stats-popover-mobile").popover("show"),l="Stats"):$("#activity-info").is(":hover")?($("#activity-info").popover("show"),
l="null",closePopups("activity-info")):$("#bodyfat-info").is(":hover")?($("#bodyfat-info").popover("show"),l="null",closePopups("bodyfat-info")):$("#custom-info").is(":hover")?($("#custom-info").popover("show"),l="null",closePopups("custom-info")):$("#protein-info").is(":hover")?($("#protein-info").popover("show"),l="null",closePopups("protein-info")):$("#carbs-info").is(":hover")?($("#carbs-info").popover("show"),l="null",closePopups("carbs-info")):$("#bmi-info").is(":hover")?($("#bmi-info").popover("show"),
l="null",closePopups("bmi-info")):$("#lbm-info").is(":hover")?($("#lbm-info").popover("show"),l="null",closePopups("lbm-info")):$("#bmr-info").is(":hover")?($("#bmr-info").popover("show"),l="null",closePopups("bmr-info")):$("#tdee-info").is(":hover")?($("#tdee-info").popover("show"),l="null",closePopups("tdee-info")):0===$(a.target).parents(".popover.in").length&&!1===p&&closePopups()});$("#stats-popover-desktop").click(function(){$("#stats-popover-desktop").attr("data-original-title","Copied!").tooltip("fixTitle").tooltip("show");
$("#stats-popover-desktop").attr("data-original-title","Copy to clipboard.").tooltip("fixTitle");copyToClipboard(c)});var m=null;$("#metric").change(function(){toggleUnits();b=getInputFields();updateResult(b,c);clearTimeout(m);m=setTimeout(function(){c=updateChart(b,c)},200)});$("#metric-text").on("click",function(){$("#metric").is(":checked")?$("#metric").prop("checked",!1):$("#metric").prop("checked",!0);toggleUnits();b=getInputFields();updateResult(b,c);clearTimeout(m);m=setTimeout(function(){c=
updateChart(b,c)},200)});$("#expert").change(function(){toggleExpert();b=getInputFields()});$("#expert-text").on("click",function(){$("#expert").is(":checked")?$("#expert").prop("checked",!1):$("#expert").prop("checked",!0);toggleExpert();b=getInputFields()});$("#time-toggle").on("click",toggleTime);$("#field-age, #field-weight, #field-feet, #field-inch, #field-cm, #field-bodyfat, #field-kcal, #field-protein, #field-carb, #time").focus(function(){$(this).animate({backgroundColor:"rgb(248,248,248)"},
200);$(this).animate({borderColor:"rgb(109,109,109)"},200)}).blur(function(){$(this).animate({backgroundColor:"white"},200);$(this).animate({borderColor:"rgb(159,159,159)"},200)});var k=null;$("#field-age, #field-feet, #field-inch, #field-cm, #bodyfat, #kcal, #protein, #carbs").on("keyup mouseup",function(){b=getInputFields();updateResult(b,c);clearTimeout(k);k=setTimeout(function(){c=updateChart(b,c)},800)});var v=null,q=null;$("#field-weight").on("keyup mouseup",function(){b=getInputFields();var a=
updateActivityKcal(b);updateResult(b,c);clearTimeout(v);v=setTimeout(function(){shuffleNumbers(b,a)},800);clearTimeout(q);q=setTimeout(function(){c=updateChart(b,c)},800)});var u=null;$("#male, #female").change(function(){b=getInputFields();updateResult(b,c);clearTimeout(u);u=setTimeout(function(){c=updateChart(b,c)},50)});$("#activity-simple").change(function(){b=getInputFields();updateResult(b,c);"0"==$(this).val()?$(".time-div, .plus-div").stop().fadeOut("slow").promise().done(function(){c=updateChart(b,
c);$("#time").val("")}):$(".time-div").stop().fadeIn("slow",function(){c=updateChart(b,c)});clearTimeout(null)});$("#activity-expert").change(function(){b=getInputFields();updateResult(b,c);var a=$(this).find("option:selected").text();"0"==$(this).val()?$(".time-div, .plus-div, #walking-div, #bicycling-div, #running-div, .next-arrow-div").stop().fadeOut().promise().done(function(){$("#time").val("");c=updateChart(b,c)}):"Walking"==a?$("#running-div, #bicycling-div, .time-div, .plus-div,  .next-arrow-div").stop().fadeOut().promise().done(function(){resetIntensity();
$("#walking-div").stop().fadeIn().promise().done(function(){c=updateChart(b,c)})}):"Running"==a?$("#walking-div, #bicycling-div, .time-div, .plus-div, .next-arrow-div").stop().fadeOut().promise().done(function(){resetIntensity();$("#running-div").stop().fadeIn().promise().done(function(){c=updateChart(b,c)})}):"Bicycling"==a?$("#walking-div, #running-div, .time-div, .plus-div, .next-arrow-div").stop().fadeOut().promise().done(function(){resetIntensity();$("#bicycling-div").stop().fadeIn().promise().done(function(){c=
updateChart(b,c)})}):$("#walking-div, #bicycling-div, #running-div, .next-arrow-div").stop().fadeOut().promise().done(function(){$(".time-div").stop().fadeIn().promise().done(function(){c=updateChart(b,c)})})});$("#activity-walking, #activity-running, #activity-bicycling").change(function(){"0"==$(this).val()?$(".next-arrow-div").fadeOut():$(".next-arrow-div").fadeIn()});$("#arrow-right").on("click",function(){$("#arrow-right").css({transition:".1s",transform:"scale(.8)"});$("#arrow-right").one($.support.transition.end,
function(){$("#arrow-right").css({transition:".1s",transform:"scale(1)"})});$("#walking-div, #running-div, #bicycling-div, .next-arrow-div").fadeOut().promise().done(function(){$(".time-div").fadeIn("fast")})});$("#time").on("keyup mouseup",function(a){b=getInputFields();$("#time").val()?$(".plus-div").stop().fadeIn("slow"):$(".plus-div").stop().fadeOut("fast");13==a.keyCode&&$("#time").val()&&r()});var r=function(){var a=getInputFields();if(sanitize(a)){var b,d;$("#add-button").off("click",r);$("#add-button").css({transition:".1s",
transform:"scale(.8)"});$("#add-button").one($.support.transition.end,function(){$("#add-button").css({transition:".1s",transform:"scale(1)"});$(".time-div, .plus-div").fadeOut("normal").promise().done(function(){$("#add-button").on("click",r)})});var e=$(a.activity.dropdown+" option:selected").val(),f=$(a.activity.dropdown).prop("selectedIndex"),g;e=$.ajax({type:"POST",url:"https://calculo.io/activity",data:e}).then(function(a){g=a})["catch"](function(){alert("something went wrong :(");g=null});
$.when(e).done(function(){null==g?($(a.activity.dropdown).val(0),$("#time").val(""),a=getInputFields(),c=updateChart(a,c),updateResult(a,c)):($(a.activity.dropdown+" option:eq("+f+")").prop("disabled",!0),$('#activity-simple option:contains("Sedentary")').text("Select"),$('#activity-expert option:contains("Sedentary")').text("Select"),b=constructActivityRow(a,g),d="#row-number-"+a.activity.tr,$(".table-activity").fadeIn("slow"),$(".table-activity tr:last").after(b),$(a.activity.dropdown).val(0),a.expert&&
$("#activity-expert").val(0),$(d).hide().fadeIn("slow").promise().done(function(){updateResult(a,c);c=updateChart(a,c);var b=convertInput(a);validate(b).valid&&isNaN(a.kcal)&&animateGrow();getInputFields()}))})}};$("#add-button").on("click",r);$(document).on("click",".activity-row",function(){b=getInputFields();var a=document.getElementById(this.id),d="#"+this.id,e=Number(this.id.replace(/^\D+/g,""));a=a.getAttribute("data-1");var f=$("#field-weight").val();var g=$("#metric").is(":checked")?f:.45359237*
f;f=Number($(d).closest("tr").children(".activity-kcal").text());var h=Number($(d).closest("tr").children(".activity-time").text()),k=Number($(d+" td:first").attr("id"));g="min"==b.time.format?Math.round(h/60*g*.9):Math.round(.9*g*h);totalActivityCalories-=f;totalIdleCalories-=g;$(a+" option:eq("+k+")").prop("disabled",!1);$(".activity-row").css("pointer-events","none");2==b.activity.tr&&($(".table-activity").fadeOut(),$('#activity-simple option:contains("Select")').text("Sedentary"),$('#activity-expert option:contains("Select")').text("Sedentary"),
totalIdleCalories=totalActivityCalories=0);$(d).fadeOut().promise().done(function(){for(var a,f,g=e;g<b.activity.tr;g++)f="#row-number-"+(g+1),a="row-number-"+g,$(f).attr("id",a);$(d).remove();b=getInputFields();updateResult(b,c);c=updateChart(b,c);a=convertInput(b);validate(a).valid&&isNaN(b.kcal)&&animateShrink();$(".activity-row").css("pointer-events","auto")})})});
function disableDropdown(a){for(var b,c,e=1;e<a.activity.tr;e++)b="row-number-"+e,c=document.getElementById(b),b=c.getAttribute("data-1"),c=c.getAttribute("data-3"),$(b+" option:eq("+c+")").prop("disabled",!0)}
function updateActivityKcal(a){var b=convertInput(a);totalIdleCalories=totalActivityCalories=0;for(var c=[],e=1;e<a.activity.tr;e++){var f="row-number-"+e;var d=document.getElementById(f);d.getAttribute("data-1");d.getAttribute("data-3");f=d.getAttribute("data-4");d=d.getAttribute("data-2");f=Math.round(d/60*b.weightKG*f);d=Math.round(d/60*b.weightKG*.9);c[e]=f;totalActivityCalories+=f;totalIdleCalories+=d}return c}
function shuffleNumbers(a,b){var c=1,e;if(c<a.activity.tr){var f=function(){setTimeout(function(){for(e="#row-number-"+c;b[c]==$(e+" td:nth-child(3)").text();)if(c++,e="#row-number-"+c,c==a.activity.tr)return;$(e+" td:nth-child(3)").text("");var d=String(b[c]);if(isNaN(d)||0>Number(d)||999999<Number(d))d="--";"--"==d?showText(e+" td:nth-child(3)",d,0,0):showText(e+" td:nth-child(3)",d,0,100);c++;c<a.activity.tr?f():setTimeout(function(){storeValues()},350)},50)};f()}}
function sanitize(a){var b=Number(a.time.value);return 0>=b||999<b||isNaN(a.weight)||0>a.weight?($(".plus-div").toggle(),$(".error-div").toggle(),$("#error-button").css({transition:".2s",transform:"scale(1.2)"}),$("#error-button").one($.support.transition.end,function(){$("#error-button").css({transition:".1s",transform:"scale(1)"});$("#error-button").one($.support.transition.end,function(){$(".time-div, .error-div").fadeOut("fast");$("#time").val("");$("#activity").val(0)})}),!1):!0}
function resetIntensity(){$("#activity-walking, #activity-running, #activity-bicycling").val(0)}function animateShrink(){$("#resultKcal").css({transition:".2s",transform:"scale(.8)"});$("#resultKcal").one("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){$("#resultKcal").css({transition:".2s",transform:"scale(1)"})})}
function animateGrow(){$("#resultKcal").css({transition:".2s",transform:"scale(1.2)"});$("#resultKcal").one("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){$("#resultKcal").css({transition:".2s",transform:"scale(1)"})})}
function constructActivityRow(a,b){var c=convertInput(a),e=a.activity.text,f=a.activity.text,d=a.activity.index,n=a.activity.dropdown;null!=a.activity.parent&&(f=e=a.activity.parent+" "+a.activity.text);if("min"==a.time.format){var g=Math.round(a.time.value/60*c.weightKG*b);c=Math.round(a.time.value/60*c.weightKG*.9);var h=a.time.value;var t=1==a.time.value?"minute":"minutes"}else g=Math.round(b*c.weightKG*a.time.value),c=Math.round(.9*c.weightKG*a.time.value),h=60*a.time.value,t=1==a.time.value?
"hour":"hours";$("#time").val("");18<e.length&&(e=e.slice(0,[18-e.length]),e=e.slice(0,-3)+"...");e='<tr class="activity-row border-bottom" id="row-number-'+a.activity.tr+'" data-1="'+n+'" data-2="'+h+'" data-3="'+d+'" data-4="'+b+'"><td id="'+d+'" title="'+f+'">'+e+'</td>\n    <td class="text-center activity-time" title="'+t+'">'+a.time.value+'</td><td class="text-center activity-kcal" title="kcal (Calories)">'+g+"</td><td><span>\u2718</span></td></tr>";totalActivityCalories+=g;totalIdleCalories+=
c;return e}
function toggleTime(){var a=getInputFields();$("#time-toggle").off("click",toggleTime);"min"==a.time.format?($("#time-format").hide(),$("#time-format").css("padding-left","4px"),$("#time-format").html(" hr")):($("#time-format").hide(),$("#time-format").css("padding-left","0px"),$("#time-format").html(" min"));$("#time-format").fadeIn("fast");a=getInputFields();var b=[];if(1<a.activity.tr){for(var c=function(){setTimeout(function(){f="#row-number-"+e;$(f+" td:nth-child(2)").text("");showText(f+" td:nth-child(2)",
b[e],0,100);e++;e<a.activity.tr?c():setTimeout(function(){$("#time-toggle").on("click",toggleTime);storeValues()},350)},50)},e=1;e<a.activity.tr;e++){var f="#row-number-"+e;var d="row-number-"+e;d=document.getElementById(d);d=Number(d.getAttribute("data-2"));"min"==a.time.format?(b[e]=d,1==b[e]?$(f+" td:nth-child(2)").prop("title","minute"):$(f+" td:nth-child(2)").prop("title","minutes")):(b[e]=1>d/60?+Number((d/60).toFixed(2)):+Number((d/60).toFixed(1)),1==b[e]?$(f+" td:nth-child(2)").prop("title",
"hour"):$(f+" td:nth-child(2)").prop("title","hours"));b[e]=String(b[e]).replace(/^0+/,"")}e=1;c()}else $("#time-toggle").on("click",toggleTime)}function stripStyle(a){for(var b,c=1;c<a.activity.tr;c++)b="#row-number-"+c,$(b).removeAttr("style")}function showText(a,b,c,e){c<b.length&&($(a).append(b[c++]),setTimeout(function(){showText(a,b,c,e)},e))}
function toggleUnits(){$("#metric").is(":checked")?($("#metric-text").animate({color:"rgb(33,33,33)"},100),document.getElementById("unit-weight").innerHTML=" kg",document.getElementById("result-lbm-info").innerHTML=" kg",document.getElementById("protein-info").setAttribute("data-content","Specifies the amount of protein per kilogram of lean body mass. Use decimal format (e.g. 1.8)"),document.getElementById("ft-and-in").style.display="none",document.getElementById("field-cm").style.display="unset",
document.getElementById("field-feet").style.width="151px",document.getElementById("unit-inch").innerHTML=" cm",document.getElementById("weight-week").innerHTML="KG/WEEK",$("#unit-weight, #unit-inch").hide().fadeIn("fast")):($("#metric-text").is(":hover"),$("#metric-text").animate({color:"rgb(169,169,169)"},100),document.getElementById("unit-weight").innerHTML=" lb",document.getElementById("result-lbm-info").innerHTML=" lb",document.getElementById("protein-info").setAttribute("data-content","Specifies the amount of protein per pound of lean body mass. Use decimal format (e.g. 0.8)"),
document.getElementById("field-cm").style.display="none",document.getElementById("ft-and-in").style.display="unset",document.getElementById("field-feet").style.width="66px",document.getElementById("unit-feet").innerHTML=" ft ",document.getElementById("unit-inch").innerHTML=" in",document.getElementById("weight-week").innerHTML="LB/WEEK",$("#unit-weight, #unit-feet, #unit-inch").hide().fadeIn("fast"))}
function toggleExpert(){$("#expert").is(":checked")?($("#expert-text").animate({color:"rgb(33,33,33)"},100),$("#expert-fields").fadeIn("fast"),$(".flipper").css("-webkit-transform","rotateY(180deg)"),$(".flipper").css("-moz-transform","rotateY(180deg)"),$(".flipper").css("-ms-transform","rotateY(180deg)"),$(".flipper").css("-o-transform","rotateY(180deg)"),$(".flipper").css("transform","rotateY(180deg)"),$("#activity-simple").css("display","none"),$("#activity-expert").css("display","unset"),$(".time-div, .plus-div, .next-arrow-div").fadeOut(),
do_once&&($("#activity-info").animate({backgroundColor:"rgb(13,142,219)"},600),$("#activity-info").effect("bounce",{times:1,distance:6},250),do_once=!1),document.getElementById("activity-info").setAttribute("data-content","Expert selected -- new activity options available")):($("#expert-text").is(":hover"),$("#expert-text").animate({color:"rgb(169,169,169)"},100),$("#expert-fields").toggle(),$(".flipper").css("-webkit-transform","rotateY(0deg)"),$(".flipper").css("-moz-transform","rotateY(0deg)"),
$(".flipper").css("-ms-transform","rotateY(0deg)"),$(".flipper").css("-o-transform","rotateY(0deg)"),$(".flipper").css("transform","rotateY(0deg)"),$("#activity-expert").css("display","none"),$("#activity-simple").css("display","unset"),$("#activity-info").animate({backgroundColor:"rgb(200,201,202)"},200),document.getElementById("activity-info").setAttribute("data-content","Select an activity from the dropdown to get a more accurate total calorie expenditure. Leave on Sedentary for a quick estimate."),
$(".time-div, .plus-div, #walking-div, #bicycling-div, #running-div, .next-arrow-div").fadeOut());$("#activity-simple, #activity-expert").val(0)}
function transitionChartWeight(){$("#chart-container-weight").addClass("original-weight-chart").clone().insertAfter("#chart-container-weight").addClass("cloned-weight-chart").appendTo("body");var a=$(".original-weight-chart").offset();a.left-=50;$(".cloned-weight-chart").css(a);$(".cloned-weight-chart").css("opacity","0");setTimeout(function(){$(".cloned-weight-chart").remove()},500)}
function transitionChartMacro(){$("#chart-container-macro").addClass("original-macro-chart").clone().insertAfter("#chart-container-macro").addClass("cloned-macro-chart").appendTo("body");var a=$(".original-macro-chart").offset();$(".cloned-macro-chart").css(a);$(".cloned-macro-chart").css("opacity","0");setTimeout(function(){$(".cloned-macro-chart").remove()},500)}
function getInputFields(){var a={age:parseInt(document.getElementById("field-age").value),weight:parseFloat(document.getElementById("field-weight").value),feet:parseInt(document.getElementById("field-feet").value),inches:parseFloat(document.getElementById("field-inch").value),cm:parseFloat(document.getElementById("field-cm").value),gender:document.getElementsByName("gender"),activity:{},time:{value:document.getElementById("time").value,format:document.getElementById("time-format").innerHTML.trim()},
view:{},bodyfat:parseFloat(document.getElementById("field-bodyfat").value),kcal:parseInt(document.getElementById("field-kcal").value),protein:parseFloat(document.getElementById("field-protein").value),carbORfat:parseInt(document.getElementById("field-carb").value)};$("#chart-container-weight").is(":visible")?a.view.animate=!1:a.view.animate=!0;$("#metric").is(":checked")?a.metric=!0:a.metric=!1;$("#expert").is(":checked")?a.expert=!0:a.expert=!1;a.slider=$(".slider").slider("option","value");if(a.expert)switch($("#activity-expert").find("option:selected").text()){case "Walking":a.activity.parent=
"Walking";a.activity.dropdown="#activity-walking";break;case "Running":a.activity.parent="Running";a.activity.dropdown="#activity-running";break;case "Bicycling":a.activity.parent="Bicycling";a.activity.dropdown="#activity-bicycling";break;default:a.activity.parent=null,a.activity.dropdown="#activity-expert"}else a.activity.parent=null,a.activity.dropdown="#activity-simple";a.activity.index=$(a.activity.dropdown).prop("selectedIndex");a.activity.value=$(a.activity.dropdown+" option:selected").val();
a.activity.text=$(a.activity.dropdown+" option:selected").text();a.activity.tr=$(".table-activity tr").length;isNaN(a.inches)&&(a.inches=0);colorExpertFields(a);storeValues();return a}
function convertInput(a){var b=a.weight;var c=a.metric?a.cm:a.feet;var e=a.inches,f=12*a.feet+a.inches,d=a.gender;d[0].checked?d="female":d[1].checked&&(d="male");b=a.metric?{weightKG:b,weightLB:2.20462262184879*b,heightM:c/100,heightCM:c,heightIN:.39370079*c}:{weightKG:.45359237*b,weightLB:b,heightM:2.54*f/100,heightCM:2.54*f,heightIN:e+12*c};b.age=a.age;b.gender=d;b.bmi=(b.weightKG/(b.heightM*b.heightM)).toFixed(1);"male"==b.gender?(b.bmr=Math.round(10*b.weightKG+6.25*b.heightCM-5*b.age+5),b.bodyfat=
1.2*b.bmi+.23*b.age-10.8-5.4):"female"==b.gender&&(b.bmr=Math.round(10*b.weightKG+6.25*b.heightCM-5*b.age-161),b.bodyfat=1.2*b.bmi+.23*b.age-5.4);isNaN(a.bodyfat)?(b.lbmLB=b.weightLB-b.bodyfat/100*b.weightLB,b.lbmKG=b.weightKG-b.bodyfat/100*b.weightKG):(b.bodyfat=a.bodyfat,b.lbmLB=b.weightLB-b.bodyfat/100*b.weightLB,b.lbmKG=b.weightKG-b.bodyfat/100*b.weightKG,b.bmr=Math.round(370+21.6*b.lbmKG));b.tdee=Math.round(b.bmr*("Sedentary"==a.activity.text?1.1:1));b.tdee=b.tdee+totalActivityCalories-totalIdleCalories;
b.target=Math.round(b.tdee*(1+.01*a.slider));isNaN(a.kcal)?toggleSlider(!0):(b.target=a.kcal,toggleSlider(!1));a.metric?(b.lbm=b.lbmKG,b.week=(7*(b.target-b.tdee)/7716.179176470765).toFixed(2)):(b.lbm=b.lbmLB,b.week=(7*(b.target-b.tdee)/3500).toFixed(2));b.week=Number(b.week);d=Math.round(100-b.target/b.tdee*100);0!=d&&(d*=-1);b.percentChange=d;a=getKetoMacros(a,b);b.protein=a.protein;b.carb=a.carb;b.fat=a.fat;b.targetKJ=Math.round(4.184*b.target);b.tdeeKJ=Math.round(4.184*b.tdee);b.bmrKJ=Math.round(4.184*
b.bmr);return b}
function calculoV8(a,b,c){a.metric||(c*=.45359237);"male"==b.gender?b.bmr=Math.round(10*c+6.25*b.heightCM-5*b.age+5):"female"==b.gender&&(b.bmr=Math.round(10*c+6.25*b.heightCM-5*b.age-161));b.tdee=Math.round(b.bmr*("Sedentary"==a.activity.text?1.1:1));b.tdee=b.tdee+totalActivityCalories-totalIdleCalories;b.target=Math.round(b.tdee*(1+.01*a.slider));isNaN(a.kcal)||(b.target=a.kcal);a=a.metric?(7*(b.target-b.tdee)/7716.179176470765).toFixed(2):(7*(b.target-b.tdee)/3500).toFixed(2);return a=Number(a)}
function toggleSlider(a){a?($(".ui-slider").slider("enable"),$(".slider-div").css("cursor","default")):($(".ui-slider").slider("disable"),$(".slider-div").css("cursor","not-allowed"))}function getKetoMacros(a,b){var c=a.protein,e=a.carbORfat,f=b.lbm,d=b.bmr,n=b.target;isNaN(c)&&(c=a.metric?1.7637:.8);isNaN(e)?(c*=f,e=1.1*d*.05/4):c*=f;return{protein:Math.round(c),carb:Math.round(e),fat:Math.round((n-4*c-4*e)/9)}}function getFitnessMacros(){}
function updateResult(a,b){var c=convertInput(a),e=validate(c);e.macros?($("#resultProtein").html(c.protein),$("#resultCarb").html(c.carb),$("#resultFat").html(c.fat),$("#labelProtein").html("protein (g)"),$("#labelCarb").html("carbs (g)"),$("#labelFat").html("fat (g)")):($("#resultProtein").html("--"),$("#resultCarb").html("--"),$("#resultFat").html("--"));e.macros&&e.target?"US"==b.country?$("#resultKcal").html(c.target):$("#resultKcal").html(c.targetKJ):$("#resultKcal").html("--");"US"==b.country?
$("#labelKcal").html("total (kcal)"):$("#labelKcal").html("total (kJ)");e.bmi?(c.bmi=+c.bmi,$("#result-bmi").html(c.bmi),30<=c.bmi?(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI of 30 and up is classified as obese."),$("#result-bmi-info").html("obese")):30>c.bmi&&25<=c.bmi?(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI of 25 to 29.9 is classified as overweight."),
$("#result-bmi-info").html("overweight")):25>c.bmi&&18.5<=c.bmi?(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI of 18.5 to 24.9 is classified as normal."),$("#result-bmi-info").html("normal")):(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI less than 18.5 is classified as underweight."),$("#result-bmi-info").html("underweight"))):
($("#result-bmi").html("--"),$("#result-bmi-info").html(""));e.bodyfat?(isNaN(a.bodyfat)?c.bodyfat=Math.round(c.bodyfat):c.bodyfat=+c.bodyfat.toFixed(1),c.bodyfat+="%",$("#result-bodyfat").html(c.bodyfat),$("#field-bodyfat").val()?$("#result-bodyfat-info").html(""):$("#result-bodyfat-info").html("estimated")):($("#result-bodyfat").html("--"),$("#result-bodyfat-info").html(""));e.lbm&&c.lbm<=a.weight?(c.lbm=Math.round(c.lbm),$("#result-lbm").html(c.lbm),$("#metric").is(":checked")?$("#result-lbm-info").html("kg"):
$("#result-lbm-info").html("lb")):($("#result-lbm").html("--"),$("#result-lbm-info").html(""));e.bmr?"US"==b.country?($("#result-bmr").html(c.bmr),$("#result-bmr-info").html("&nbspkcal")):($("#result-bmr").html(c.bmrKJ),9999<c.bmrKJ?$("#result-bmr-info").html("&nbsp&nbsp&nbspkJ"):$("#result-bmr-info").html("&nbspkJ")):($("#result-bmr").html("--"),$("#result-bmr-info").html(""));e.tdee?"US"==b.country?($("#result-tdee").html(c.tdee),$("#result-tdee-info").html("&nbspkcal")):($("#result-tdee").html(c.tdeeKJ),
9999<c.tdeeKJ?$("#result-tdee-info").html("&nbsp&nbsp&nbspkJ"):$("#result-tdee-info").html("&nbspkJ")):($("#result-tdee").html("--"),$("#result-tdee-info").html(""));c.week=c.week.toFixed(2);if(b.slider_calories)e.week?0<c.week?$("#result-week").html("+"+c.week):$("#result-week").html(c.week):$("#result-week").html("--"),a.metric?$("#weight-week").html("KG/WEEK"):$("#weight-week").html("LB/WEEK");else{"US"==b.country?$("#weight-week").html("CALORIES"):$("#weight-week").html("KILOJOULES");if(250<c.percentChange||
-250>c.percentChange)c.percentChange="--";0<c.percentChange&&(c.percentChange="+"+c.percentChange);isNaN(c.percentChange)?$("#result-week").html("--"):$("#result-week").html(c.percentChange+"%")}b.slider_calories?("US"==b.country?$(".slider-title").html("Calorie "):$(".slider-title").html("Kilojoule "),isNaN(c.percentChange)&&"--"!=c.percentChange?0<a.slider?$(".slider-text").html(" "+a.slider+"% Surplus \u25b2"):0>a.slider?(a.slider*=-1,$(".slider-text").html(" "+a.slider+"% Deficit \u25bc")):$(".slider-text").html(" Maintain Weight"):
9999<a.kcal||-9999>a.kcal?(c.percentChange="--",$(".slider-text").html(" "+c.percentChange+"%&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp")):0<c.percentChange?$(".slider-text").html(" "+c.percentChange+"% Surplus \u25b2"):0>c.percentChange?(c.percentChange*=-1,$(".slider-text").html(" "+c.percentChange+"% Deficit \u25bc")):$(".slider-text").html(" Maintain Weight")):(e.week&&e.macros||(c.week="--"),$(".slider-title").html("Dietary "),a.metric?0<parseFloat(c.week)?$(".slider-text").html(" "+
c.week+" kg/week \u25b2"):0>parseFloat(c.week)?$(".slider-text").html(" "+c.week+" kg/week \u25bc"):$(".slider-text").html(" "+c.week+" kg/change"):0<parseFloat(c.week)?$(".slider-text").html(" "+c.week+" lb/week \u25b2"):0>parseFloat(c.week)?$(".slider-text").html(" "+c.week+" lb/week \u25bc"):$(".slider-text").html(" "+c.week+" lb/change"));9999<a.kcal&&$("#result-bmi, #result-bodyfat, #result-lbm, #result-bmr, #result-tdee, #result-week").html("--");c.week=Number(c.week);return c}
function validate(a){var b={};0>a.protein||999<a.protein||0>a.carb||999<a.carb||0>a.fat||999<a.fat||isNaN(a.protein+a.carb+a.fat)?b.macros=!1:b.macros=!0;0>a.bmi||99<a.bmi||isNaN(a.bmi)?b.bmi=!1:b.bmi=!0;0>a.bodyfat||99<a.bodyfat||isNaN(a.bodyfat)?b.bodyfat=!1:b.bodyfat=!0;0>a.lbm||999<a.lbm||isNaN(a.lbm)?b.lbm=!1:b.lbm=!0;0>a.bmr||2E4<a.bmr||isNaN(a.bmr)?b.bmr=!1:b.bmr=!0;0>a.tdee||2E4<a.tdee||isNaN(a.tdee)?b.tdee=!1:b.tdee=!0;-15>a.week||15<a.week||isNaN(a.week)?b.week=!1:b.week=!0;0>a.target||
2E4<a.target||isNaN(a.target)?b.target=!1:b.target=!0;b.valid=b.macros&&b.target?!0:!1;return b}function updateScreen(a,b,c,e,f,d,n,g){updateResult(n,g);e=performance.now();drawChartMacroOLD(a,c);drawChartWeightOLD(a,c);f=performance.now();console.log("Call to do OLD charts took "+(f-e)+" milliseconds.");0==b&&(a=1,$("#chart-container-weight, .flip-container").fadeIn("normal"),drawChartMacroOLD(a,c),drawChartWeightOLD(a,c),a=0);b=1;storeValues(void 0,void 0,void 0,void 0,b);return[a,b]}
function updateScreen2(a,b,c){c=updateResult(a,b);var e=validate(c);$("#chart-container-weight, .flip-container").fadeIn("normal");drawChartMacro(a,c,b,e);drawChartWeight(a,c,b,e);return b}
function updateChart(a,b){var c=convertInput(a),e=validate(c);e.valid?($("#chart-container-weight, .flip-container").fadeIn("slow"),b.animate_chart||(transitionChartWeight(),a.expert||transitionChartMacro()),drawChartMacro(a,c,b,e),drawChartWeight(a,c,b,e),b.animate_chart=!1):($("#chart-container-weight, .flip-container").fadeTo(100,0).promise().done(function(){$("#chart-container-weight, .flip-container").toggle();$("#chart-container-weight, .flip-container").css("opacity","1")}),b.animate_chart=
!0);return b}function closePopups(a){for(var b="#stats-popover-mobile #activity-info #bodyfat-info #custom-info #protein-info #carbs-info #bmi-info #bmr-info #tdee-info #lbm-info".split(" "),c=0,e=0,f=1;f<=b.length;f+=1)$(b[c]).attr("id")==a?e++:$(b[c]).popover("hide"),c++}
function copyToClipboard(a){var b=getInputFields(),c=convertInput(b);if("US"==a.country){var e=c.target;var f="kcal"}else e=c.targetKJ,f="kJ";var d="male"==c.gender?"Male":"Female";a="Generated by calculo.io/keto-calculator\n***\n";a=$("#metric").is(":checked")?a+("Gender: "+d+" | Age: "+c.age+" | Weight: "+c.weightKG+" kg | Height: "+c.heightCM+" cm\n\ns"):a+("Gender: "+d+" | Age: "+c.age+" | Weight: "+c.weightLB+" lb | Height: "+b.feet+"'"+b.inches+'"\n\n');0<b.slider?a+="Calorie Goal: "+b.slider+
"% Surplus \u25b2  \n\n":0===b.slider?a+="Calorie Goal: 0% Change  \n\n":(b.slider*=-1,a+="Calorie Goal: "+b.slider+"% Deficit \u25bc  \n\n");a+="Protein: "+c.protein+"g  \nCarbs: "+c.carb+"g  \nFat: "+c.fat+"g  \n\n";a+="Target: "+e+" "+f;$("#text-area").text(a);$("#copy-button").click()}
function printResult(a,b,c,e,f){a=calculoio(b,f);b=errorCheckPass(b);var d=a[20];b?($("#resultProtein").html(a[0]),$("#resultCarb").html(a[1]),$("#resultFat").html(a[2]),$("#labelProtein").html("protein (g)"),$("#labelCarb").html("carbs (g)"),$("#labelFat").html("fat (g)")):($("#resultProtein").html("--"),$("#resultCarb").html("--"),$("#resultFat").html("--"));0==c?(b?$("#resultKcal").html(a[5]):$("#resultKcal").html("--"),"US"==f?$("#labelKcal").html("total (kcal)"):$("#labelKcal").html("total (kJ)")):
1==c?(b?$("#resultKcal").html(a[17]):$("#resultKcal").html("--"),"US"==f?$("#labelKcal").html("protein (kcal)"):$("#labelKcal").html("protein (kJ)")):2==c?(b?$("#resultKcal").html(a[18]):$("#resultKcal").html("--"),"US"==f?$("#labelKcal").html("carbs (kcal)"):$("#labelKcal").html("carbs (kJ)")):3==c&&(b?$("#resultKcal").html(a[19]):$("#resultKcal").html("--"),"US"==f?$("#labelKcal").html("fat (kcal)"):$("#labelKcal").html("fat (kJ)"));0>a[7]||100<a[7]||isNaN(a[7])?($("#result-bmi").html("--"),$("#result-bmi-info").html("")):
($("#result-bmi").html(a[7]),30<=a[7]?(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI of 30 and up is classified as obese."),$("#result-bmi-info").html("obese")):30>a[7]&&25<=a[7]?(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI of 25 to 29.9 is classified as overweight."),$("#result-bmi-info").html("overweight")):25>a[7]&&18.5<=
a[7]?(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI of 18.5 to 24.9 is classified as normal."),$("#result-bmi-info").html("normal")):(document.getElementById("bmi-info").setAttribute("data-content","Body Mass Index: the value derived from your weight and height. BMI less than 18.5 is classified as underweight."),$("#result-bmi-info").html("underweight")));0>a[8]||99<a[8]||isNaN(a[8])?($("#result-bodyfat").html("--"),
$("#result-bodyfat-info").html("")):(a[8]+="%",$("#result-bodyfat").html(a[8]),$("#field-bodyfat").val()?$("#result-bodyfat-info").html(""):$("#result-bodyfat-info").html("estimated"));0>a[16]||999<a[16]||isNaN(a[16])?($("#result-lbm").html("--"),$("#result-lbm-info").html("")):($("#result-lbm").html(a[16]),$("#metric").is(":checked")?$("#result-lbm-info").html("kg"):$("#result-lbm-info").html("lb"));0>a[3]||2E4<a[3]||isNaN(a[3])?($("#result-bmr").html("--"),$("#result-bmr-info").html("")):($("#result-bmr").html(a[3]),
"US"==f?$("#result-bmr-info").html("kcal"):9999<a[3]?$("#result-bmr-info").html("&nbspkJ"):$("#result-bmr-info").html("kJ"));0>a[4]||2E4<a[4]||isNaN(a[4])?($("#result-tdee").html("--"),$("#result-tdee-info").html("")):($("#result-tdee").html(a[4]),"US"==f?$("#result-tdee-info").html("kcal"):9999<a[4]?$("#result-tdee-info").html("&nbspkJ"):$("#result-tdee-info").html("kJ"));if("calorie"==e)$("#metric").is(":checked")?$("#weight-week").html("KG/WEEK"):$("#weight-week").html("LB/WEEK"),isNaN(a[6])||
0>a[3]||2E4<a[3]||2E4<a[5]||-2E4>a[5]?$("#result-week").html("--"):$("#result-week").html(a[6]);else{"US"==f?$("#weight-week").html("CALORIES"):$("#weight-week").html("KILOJOULES");if(250<d||-250>d)d="--";0<d&&(d="+"+d);isNaN(d)?$("#result-week").html("--"):$("#result-week").html(d+"%")}$("#expert").is(":checked")}
function printSliderDescription(a,b,c){var e=calculoio(b),f=e[6],d=e[20];if(isNaN(f)||0>e[3]||2E4<e[3]||2E4<e[5]||-2E4>e[5])f="--";if(250<d||-250>d)d="--";a.slider_calories?("US"==c?$(".slider-title").html("Calorie "):$(".slider-title").html("Kilojoule "),isNaN(d)&&"--"!=d?0<b?$(".slider-text").html(" "+b+"% Surplus \u25b2"):0>b?(b*=-1,$(".slider-text").html(" "+b+"% Deficit \u25bc")):$(".slider-text").html(" Maintain Weight"):0<d?$(".slider-text").html(" "+d+"% Surplus \u25b2"):0>d?(d*=-1,$(".slider-text").html(" "+
d+"% Deficit \u25bc")):$(".slider-text").html(" Maintain Weight")):($(".slider-title").html("Dietary "),$("#metric").is(":checked")?0<parseFloat(f)?$(".slider-text").html(" "+f+" kg/week \u25b2"):0>parseFloat(f)?$(".slider-text").html(" "+f+" kg/week \u25bc"):$(".slider-text").html(" "+f+" kg/change"):0<parseFloat(f)?$(".slider-text").html(" "+f+" lb/week \u25b2"):0>parseFloat(f)?$(".slider-text").html(" "+f+" lb/week \u25bc"):$(".slider-text").html(" "+f+" lb/change"))}
function maxLengthCheck(a){a.value.length>a.maxLength&&(a.value=a.value.slice(0,a.maxLength))}
function colorExpertFields(a){isNaN(a.bodyfat)?document.getElementById("bodyfat").style.color="gray":document.getElementById("bodyfat").style.color="black";isNaN(a.kcal)?document.getElementById("kcal").style.color="gray":document.getElementById("kcal").style.color="black";isNaN(a.protein)?document.getElementById("protein").style.color="gray":document.getElementById("protein").style.color="black";isNaN(a.carbORfat)?document.getElementById("carbs").style.color="gray":document.getElementById("carbs").style.color=
"black"}
function calculoio(a,b,c){var e=document.getElementsByName("gender"),f=parseInt(document.getElementById("field-age").value),d=parseFloat(document.getElementById("field-weight").value);isNaN(c)||(d=c);c=parseFloat(document.getElementById("field-feet").value);var n=parseFloat(document.getElementById("field-inch").value);$("#field-inch").val()||(n=0);var g=n+12*c,h=document.getElementById("activity-simple").value;var t="FIX NEAR ROW 1446";if(0==h){var l=1.1;t="Sedentary (No Exercise)"}else l=1;if($("#metric").is(":checked")){var p=
c/100;var m=c;g=d;var k=2.20462262184879*d}else p=2.54*g/100,m=2.54*g,g=.45359237*d,k=d;p=g/(p*p);if(!0===e[1].checked){var v="Male";var q=1.2*p+.23*f-10.8-5.4;var u=10*g+6.25*m-5*f+5}else!0===e[0].checked&&(v="Female",q=1.2*p+.23*f-5.4,u=10*g+6.25*m-5*f-161);var r=k-q/100*k;m=g-q/100*g;$("#field-bodyfat").val()&&(q=$("#field-bodyfat").val(),r=k-q/100*k,m=g-q/100*g,u=370+21.6*m);l=u*l+totalActivityCalories-totalIdleCalories;$("#field-bodyfat").val()?document.getElementById("bodyfat").style.color=
"black":document.getElementById("bodyfat").style.color="gray";$("#field-kcal").val()?document.getElementById("kcal").style.color="black":document.getElementById("kcal").style.color="gray";$("#field-protein").val()?document.getElementById("protein").style.color="black":document.getElementById("protein").style.color="gray";$("#field-carb").val()?document.getElementById("carbs").style.color="black":document.getElementById("carbs").style.color="gray";e=l*(1+.01*a);$("#field-kcal").val()?(e=$("#field-kcal").val(),
$(".ui-slider").slider("disable"),$(".slider-div").css("cursor","not-allowed")):($(".ui-slider").slider("enable"),$(".slider-div").css("cursor","default"));$("#metric").is(":checked")?(g=0==h?1.7637:1==h?1.8265:2==h?1.8894:3==h?1.9522:4==h?2.015:5==h?2.0779:6==h?2.1407:7==h?2.2035:1.7637,h=m):(g=0==h?.8:1==h?.8285:2==h?.857:3==h?.8855:4==h?.914:5==h?.9425:6==h?.971:7==h?.9995:.8,h=r);$("#field-protein").val()&&(g=$("#field-protein").val());$("#field-carb").val()?(k=$("#field-carb").val(),g*=h,m=k):
(g*=h,m=1.1*u*.05/4);k=(e-4*g-4*m)/9;r=$("#metric").is(":checked")?(7*(e-l)/7716.179176470765).toFixed(2):(7*(e-l)/3500).toFixed(2);0<r&&(r="+"+r);var w=4*Math.round(g);var x=4*Math.round(m);var y=9*Math.round(k);"AU"==b&&(e*=4.184,l*=4.184,u*=4.184,w=Math.round(4.184*w),x=Math.round(4.184*x),y=Math.round(4.184*y));var z=Math.round(100-e/l*100);0!=z&&(z*=-1);storeValues("dummyNaN",-1,-1,b);return[Math.round(g),Math.round(m),Math.round(k),Math.round(u),Math.round(l),Math.round(e),r,+p.toFixed(2),Math.round(q),
v,f,d,c,n,t,a,+h.toFixed(1),w,x,y,z]}function errorCheckPass(a){a=calculoio(a);return isNaN(a[0])||0>a[0]||999<a[0]||0>a[1]||999<a[1]||0>a[2]||999<a[2]||1E4<a[4]||isNaN(a[5])?0:1}function between(a,b,c){return a>=b&&a<=c}
function drawChartMacro(a,b,c,e){if("US"==c.country&&e.valid){var f=4*b.protein;var d=4*b.carb;var n=9*b.fat;var g=["kcal","gram"]}else"AU"==c.country&&e.valid&&(f=Math.round(16.736*b.protein),d=Math.round(16.736*b.carb),n=Math.round(37.656*b.fat),g=["kJ","gram"]);e.valid?(a=b.protein,e=b.carb,b=b.fat):b=e=a=n=d=f=0;Highcharts.setOptions({chart:{style:{fontFamily:"Verdana"}},plotOptions:{series:{animation:c.animate_chart}}});Highcharts.chart("chart-container-macro",{chart:{type:"column"},title:{text:"MACROS\n",
style:{fontSize:"27px",fontWeight:"bold"}},credits:!1,xAxis:{categories:g,crosshair:!0},yAxis:{allowDecimals:!1,min:0,title:{text:""}},tooltip:{backgroundColor:null,borderWidth:0,shadow:!1,headerFormat:'<span style="text-align:left;font-size:10px">{point.key}</span><table>',pointFormat:'<tr><td style="text-align:left;font-weight:bold;color:{series.color};padding:0">{series.name}:&nbsp</td><td style="text-align:left; padding:0"><b>{point.y:1f}</b></td></tr>',footerFormat:"</table>",shared:!0,useHTML:!0,
borderRadius:0},plotOptions:{column:{pointPadding:.2,borderWidth:0}},series:[{name:"protein",data:[f,a],pointWidth:10},{name:"carbs",data:[d,e],pointWidth:10},{name:"fat",data:[n,b],pointWidth:10}]})}
function drawChartWeight(a,b,c,e){var f=new Date,d=[],n=[],g=0;var h=b.week;var t=10;var l=a.metric?b.weightKG:b.weightLB;var p=a.slider;if(0>p){var m=!0;p*=-1}else m=!1;if(a.kcal){m=a.kcal<b.tdee?!0:!1;var k=100-a.kcal/b.tdee*100;0>k&&(k*=-1);p=1>k?0:1<=k&&10>k?10:10<=k&&20>k?20:20<=k&&30>k?30:40;100<k&&(t=20)}k=l;for(var v=1;30>=v;v+=1){n.push(l);h=calculoV8(a,b,l);l+=h;h=f.getDate();var q=f.getMonth()+1;a.metric?d.push(h+"/"+q):d.push(q+"/"+h);f.setDate(f.getDate()+7);g++}a=l;p=(40-p)/2;m?(m=k+
p,k=a-p):(m=a+p,k-=p);e.valid||(d=[],n=[]);Highcharts.setOptions({chart:{style:{fontFamily:"Verdana"}},plotOptions:{series:{animation:c.animate_chart},line:{marker:{enabled:!1}}}});Highcharts.chart("chart-container-weight",{title:{text:"FORECAST",style:{fontSize:"27px",fontWeight:"bold"}},subtitle:{text:""},credits:!1,tooltip:{backgroundColor:"rgba(255,255,255,0.85)",borderColor:"rgb(204,204,204)",borderWidth:1,borderRadius:0,formatter:function(){return'<span style="text-align:0   ; font-size: 10px">'+
this.x+"</span><br/>weight: <b>"+ +this.y.toFixed(1)+"</b>"}},xAxis:{categories:d},yAxis:{min:k,max:m,tickInterval:t,title:{text:""}},legend:{layout:"vertical",align:"right",verticalAlign:"middle"},plotOptions:{},series:[{id:"forecast",showInLegend:!1,name:"weight",data:n}]})};
